name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  deployment:
    name: Deployment
    needs: ci
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::018955960688:role/Nordcloud-Clouduty
          aws-region: eu-central-1
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - name: Deploy stack
        run: npx cdk deploy --all --require-approval never

  version-bump:
    name: 'Version bump'
    runs-on: ubuntu-latest
    needs: deployment
    permissions:
      contents: write
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          commit-message: 'version bump to {{version}} [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
          
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
    